services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./app:/app"
    command: sh -c "make dev"

  caddy:
    image: caddy:2.6
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "./public:/etc/caddy/public"
      - caddy_data:/data
      - caddy_config:/config


volumes:
  caddy_data:
  caddy_config: