services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: gorokhismyname/devops-for-programmers-project-74:attempt1
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV:-test}
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_NAME=${DATABASE_NAME:-postgres}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}
    command: sh -c "make test"

volumes:
  db_data: