services:
  app:
    # image: gorokhismyname/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8080:8080"
    command: sh -c "make test"