name: Build and push Docker image

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Run tests using Docker Compose
      run: docker-compose -f docker-compose.yml up --abort-on-container-exit
    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.production
        push: true
        tags: gorokhismyname/devops-for-programmers-project-74:latest
